# Instance Group Section of the Deployment manifest for Tornado Mode
# Check README.md for properites examples
instance_groups:
- name: jmeter_launchers
  instances: 1
  vm_type: default
  stemcell: default_stemcell
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: jmeter_tornado
    release: jmeter-tornado
    properties: ....
