# Instance Group Section of the Deployment manifest for Storm Mode
# Check README.md for properites examples

instance_groups:
- name: workers
  instances: 3
  vm_type: default
  stemcell: default_stemcell
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: jmeter_storm_worker
    release: jmeter-tornado

- name: storm
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: default_stemcell
  azs: [z1]
  networks:
  - name: default
  jobs:
  - name: jmeter_storm
    release: jmeter-tornado
    properties: .....
